### ISSUE TITLE
Get Contributing Guidelines established early

### ISSUE THREAD

**Issue by anaran** [mozilla-b2g/raptor#29]
Hi!

From following numerous mozilla projects I have some general feedback for this young project.

https://www.npmjs.com/package/gaia-raptor has very little information, due to the minimal package.json project in this repository.

https://github.com/mozilla-b2g/raptor/blob/master/package.json#L23 suggest to file issues at
https://bugzilla.mozilla.org

A more specific link might help getting the issues into the right channels, e.g.
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20OS&component=Gaia::PerformanceTest

This github repo has issues turned on as well. This might set you up for looking at bugzilla and github issues, which might not be what you want (issues can be disabled in github if desired).

mozilla projects at github have various different contribution guidelines, which I have long thought are a nuisance for people contributing to multiple. At least the differences should be kept to a minimum.

Some information to look at and perhaps adopt one as (yet missing)
https://github.com/mozilla-b2g/raptor/blob/master/CONTRIBUTING.md

Notice how only `kuma` has github issues enabled.
Many request certain formats for commit messages in pull requests:

https://github.com/mozilla/olympia/blob/master/CONTRIBUTING.rst
https://github.com/mozilla-b2g/gaia/blob/master/CONTRIBUTING.md
https://github.com/mozilla/kuma/blob/master/CONTRIBUTING.md
https://github.com/mozilla/bedrock/blob/master/CONTRIBUTING.md
https://github.com/mozilla/gecko-dev/blob/master/README.txt

Only `olympia` has github wiki enabled, but does not use it.

Best,
Adrian

**Comment by eliperelman** [comment]
Thanks @anaran for the suggestions! I'll get the readme, bugzilla component, and close the issues on this repo. I'll also look over the contributing file and figure out which to adopt.

**Comment by eliperelman** [comment]
Closing issue to remove issues.
